### PR TITLE
Adding the magic constant "anything", closes #20

### LINKED ISSUE #20: sure.any()
sometimes I wanna check a value of a key from a dictionary, for example, but the values from the other keys don't really matter. Currently there is no way to do this but copy all the values from the other dict on the assert dict. I propose the following:

``` python
a = {'key': 1, 'other_key': 4}
b = {'key': 1, 'other_key': sure.any()}

assert that(a).equals(b) // True
```
In the context of this code, the value of 'other_key' is completely unnecessary to test, so i create an instance of sure.any to match with it and 'any' is equal to everything.

This is not a new concept, some other libraries already implement it, like Jasmine.

direct link:

[http://pivotal.github.com/jasmine/#section-Matching_Anything_with_<code>jasmine.any</code>](http://pivotal.github.com/jasmine/#section-Matching_Anything_with_<code>jasmine.any</code>)

I'm sorry, the link was getting escaped so I had to do this.

### PR DESCRIPTION
**Pull request by clarete**

### CODE REVIEW

**Comment by timofurrer** [comment]
I like that, What's wrong @gabrielfalcao ? 

@clarete seems to have a merge conflict ...

**Comment by timofurrer** [comment]
I have some projects which are kind of depending on this feature. @gabrielfalcao could you please merge/review this PR? Thanks

**Comment by timofurrer** [comment]
@clarete as soon as you update this PR I'm ready to merge :cake:

**Comment by gabrielfalcao** [comment]
Oh God, I'm so sorry for missing this one.
Let's merge it!

**Comment by timofurrer** [comment]
This is implemented by #113 
I rebased @clarete branch to master.

:beers:

**Pull request closed without merging**
