### PR TITLE
Fix assertions on raises exception type mismatch

### PR DESCRIPTION
**Pull request by codito**

### CODE REVIEW

**Comment by timofurrer** [comment]
Could you please solve the merge conflicts?

Thanks :beers:

**Comment by timofurrer** [comment]
push

**Comment by codito** [comment]
@timofurrer not sure whether the issue/fix still apply on master (the PR is very old :)). I will check and clean it up this week.

**Comment by timofurrer** [comment]
Yeah, I know. It's quite old. Sorry for that. 
Thanks for having a look at it! If you have any questions regarding the current implementation please don't hesitate to ask on gitter: https://gitter.im/gabrielfalcao/sure

**Comment by codito** [comment]
Abandoned in favor of https://github.com/gabrielfalcao/sure/pull/118

**Pull request closed without merging**
