### PR TITLE
Remove shebang line

### PR DESCRIPTION
**Pull request by nijel**
These are not executables, so the shebang does not make much sense.

### CODE REVIEW

**Comment by timofurrer** [comment]
:+1:

**Comment by timofurrer** [comment]
Could you please update this PR? 

Thanks :beers:

**Comment by nijel** [comment]
Why? There are no merge conflicts...

Anyway if you want to regenerate it, just do:

```sh
find sure -name '*.py' | xargs sed -i '/^#!\/usr\/bin\/env python/D'
```

**Comment by timofurrer** [comment]
Yeah, you're right. sorry. I tagged it wrongly. I thought about the update because of the failed tests.
However, I'm gonna merge it now, since it won't fail the build.

**Comment by timofurrer** [comment]
GitHub just screwed up a little. When I merged there was a notification saying that something went wrong: The change is somehow merged in master but the PR is still here.
Sorry about that - I'm now closing this one - Don't be confused, because it seems to be in master.

**Comment by nijel** [comment]
I think some of the confusion comes from the fact that I've removed source repo meanwhile (honestly I didn't expect that something will get merged after two years of no activity).

**Comment by timofurrer** [comment]
Yes, I understand. 
Since last weekend I'm a new maintainer and will help gabriel with this repository. 

So, there will be more updates :)

**Pull request closed without merging**
